build: upgrade build plugins
micronaut-projects/micronaut-kubernetes pull request #518
Opened 2022-11-25 12:46 UTC by dradosevic

2023-01-25 06:53 UTC, sdelamo requested changes
Could you merge master into this branch and set micronaut gradle plugin version to 3.7.0 ?

2023-02-14 10:50 UTC, sdelamo commented
ping @dradosevic

2023-02-24 12:56 UTC, dradosevic commented
@sdelamo merged master and upgraded micronaut gradle plugin to 3.7.0

2023-02-27 09:54 UTC, sdelamo approved these changes

2023-02-27 09:54 UTC, merged