Migrate to new configuration asciidoc macro and build plugin to 5.4.4
micronaut-projects/micronaut-kubernetes pull request #530
Opened 2023-02-03 16:31 UTC by wetted

closes #527

2023-02-06 12:36 UTC, sdelamo requested changes

2023-02-06 12:36 UTC, sdelamo commented on settings.gradle
> +    id 'io.micronaut.build.shared.settings' version '5.4.4'
```suggestion
    id 'io.micronaut.build.shared.settings' version '5.4.5'
```

2023-02-08 14:29 UTC, sdelamo approved these changes

2023-02-08 14:30 UTC, sdelamo commented
@n0tl3ss could you merge this in once it is green?

2023-02-08 14:32 UTC, n0tl3ss approved these changes

2023-02-08 14:34 UTC, n0tl3ss commented
Hi @sdelamo. I think we are getting
 ```
2023-02-06T13:00:00.7562540Z -----------
2023-02-06T13:00:00.7563097Z * What went wrong:
2023-02-06T13:00:00.7564163Z Execution failed for task ':kubernetes-client-processor:findBaseline'.
2023-02-06T13:00:00.7565743Z > Failed to read releases from https://api.github.com/repos/micronaut-projects/micronaut-kubernetes/releases
``` 

because of github rate limit. Should we rerun it or can we just merge it?

2023-02-09 14:50 UTC, merged